### ISSUE TITLE
Review command ID categories and those who begin with `truffle-contract`

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#168]
The `package.json` file defines two different categories for commands displayed in the Command Palette, `Truffle` and `Blockchain`. To avoid confusion, we should remove the `Blockchain` category. And some command IDs are duplicated, for instance, `truffle-vscode.showWelcomePage`.

Moreover, in `package.json` there are 3 commands that begin with `truffle-contract`.

```
truffle-contract.copyByteCode
truffle-contract.copyDeployedByteCode
truffle-contract.copyABI
```

This might be confusing given the rest of command IDs begin with `truffle-vscode`. Moreover, those command IDs have duplicated definitions, with different `title` and `category`. Compare category `Blockchain` (which is the old one) to category `Truffle`. We should keep only the `Truffle` category.

https://github.com/trufflesuite/vscode-ext/blob/c3868821895f54399541e3c33b1f1f4a41a3d9ad/package.json#L104-L118

https://github.com/trufflesuite/vscode-ext/blob/c3868821895f54399541e3c33b1f1f4a41a3d9ad/package.json#L211-L225

### Tasks

- [x] Put commands in the `Blockchain` category to `Truffle` category.
- [x] Rename command prefix `truffle-contract` to `truffle-vscode` to match the rest of the command IDs.
- [x] Remove these duplicated command IDs that belong to the `Blockchain` category.

---

@kevinbluer @xhulz @michaeljohnbennett thoughts about this?
