### ISSUE TITLE
Remove outdated Welcome Page

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#277]
As discussed in https://github.com/trufflesuite/vscode-ext/pull/148#issuecomment-1184908408, the content of the _Welcome Page_, triggered by `Truffle: Show Welcome Page` command is outdated. It has been superseded by the _Walkthrough_ https://github.com/trufflesuite/vscode-ext/pull/148. Thus, we should remove the _Welcome Page_.

## Tasks

- [ ] Remove _Welcome Page_, both under `resources/welcome/` and `src/pages/`
- [ ] Remove any unused image referenced in the _Welcome Page_
- [ ] Remove `jquery-*.js` and `main.js` usage from `prereqs.html`
- [ ] Remove `jquery-*.js` and `main.js` under `resources/welcome`. This would solve https://github.com/trufflesuite/vscode-ext/issues/124
- [ ] Remove `Truffle: Show Welcome Page` command
